version: '3'

services:
 php:
    build: 
      context: .
      dockerfile: ./php/Dockerfile
    volumes: 
      - ./src/:/php
 web:
     build:
      context: .
      dockerfile: ./nginx/Dockerfile
     ports:
      - 8080:80
     expose:
      - "8000"
     depends_on:
      - php
     volumes:
      - ./src/:/php
 mysql:
     build:
        context: .
        dockerfile: ./mysql/Dockerfile
     ports:
       - 3307:3306
     env_file: .env.dev
     environment:
        TZ: 'Asia/Tokyo'
     volumes:
       - mysql-volume:/var/lib/mysql
 node:
      build:
        context: .
        dockerfile: ./node/Dockerfile
      working_dir: /frontend
      ports:
        - 4200:4200
        - 4201:4201
      volumes:
        - ./frontend:/frontend
      tty: true
 minio:
      image: 'minio/minio'
      environment:
          MINIO_ROOT_USER: "miniotestuser"
          MINIO_ROOT_PASSWORD: "miniotestpassword"
      entrypoint: bash
      command: -c "/opt/bin/minio server /export --address :9999 --console-address :9001"
      volumes:
          - ./minio/data:/export
      ports:
          - '9900:9999'
          - '9001:9001'

volumes:
   mysql-volume:
    name: database-volumes